# Generated by Django 2.1.1 on 2018-12-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pictureself_ids_json',
        ),
    ]
