# Generated by Django 2.1.1 on 2019-01-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nam',
            field=models.CharField(default='', max_length=32),
        ),
    ]
