# Generated by Django 2.1.1 on 2019-01-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictureselfs', '0002_auto_20190109_1728'),
        ('variants', '0002_variant_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='creator',
        ),
        migrations.AddField(
            model_name='variant',
            name='pictureself',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pictureselfs.Pictureself'),
            preserve_default=False,
        ),
    ]
