# Generated by Django 2.1.1 on 2019-01-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0003_auto_20190127_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='original_name',
            field=models.CharField(blank='True', max_length=200, null='True'),
        ),
    ]
