# Generated by Django 2.1.1 on 2019-02-05 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('variants', '0005_auto_20190131_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='variant',
            name='pictureselfs',
            field=models.ManyToManyField(related_name='pictureself_variants', to='pictureselfs.Pictureself'),
        ),
    ]
