# Generated by Django 2.1.1 on 2019-02-05 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0006_auto_20190205_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='variant',
            name='pictureselfs',
            field=models.ManyToManyField(related_name='variants', to='pictureselfs.Pictureself'),
        ),
    ]
