# Generated by Django 2.1.1 on 2019-02-05 23:21

from django.db import migrations, models
import variants.models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0007_auto_20190205_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=variants.models.get_file_path, width_field='width'),
        ),
    ]
