# Generated by Django 2.1.1 on 2019-02-05 23:31

from django.db import migrations, models
import variants.models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0008_auto_20190206_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='height',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='width',
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(upload_to=variants.models.get_file_path),
        ),
    ]
