# Generated by Django 2.1.1 on 2020-04-25 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0009_auto_20190206_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='pictureselfs',
        ),
    ]
