# Generated by Django 2.1.1 on 2019-01-09 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictureselfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureself',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictureselfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
