# Generated by Django 2.1.1 on 2019-01-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictureselfs', '0002_auto_20190109_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictureself',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pictureself',
            name='width',
        ),
    ]
