# Generated by Django 2.1.1 on 2019-01-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictureselfs', '0003_auto_20190127_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictureself',
            name='original_feature_ids_json',
        ),
    ]
