# Generated by Django 2.1.1 on 2019-04-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureselfs', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureself',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
