# Generated by Django 2.1.1 on 2019-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureselfs', '0002_auto_20190109_1728'),
        ('features', '0002_feature_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='creator',
        ),
        migrations.AddField(
            model_name='feature',
            name='pictureself',
            field=models.ManyToManyField(related_name='features', to='pictureselfs.Pictureself'),
        ),
    ]
