# Generated by Django 2.1.1 on 2019-01-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190127_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='pictureself',
            new_name='pictureselfs',
        ),
    ]
